name = "chopper-news"
main = "src/index.ts"
compatibility_date = "2024-12-01"
# Enable Node.js compat for article-extractor
compatibility_flags = ["nodejs_compat"]

[vars]
# Thêm các biến môi trường không nhạy cảm ở đây nếu có

[[d1_databases]]
binding = "DB"
database_name = "chopper-news-db"
database_id = "8a7396f5-6e65-46e7-96c6-61b3b3d9e842"
migrations_dir = "migrations"

[ai]
binding = "AI"


[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1